name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setupNode
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: run backend tests
        run: yarn run test

      - name: Run Playwright tests
        run: yarn run playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
